//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wrmsms
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:SMSwsdl", ConfigurationName="wrmsms.SMSwsdlPortType")]
    public interface SMSwsdlPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SMSwsdl#SMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> sendSMSAsync(string domain, string username, string password, string from, string to, string text, int isflash);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SMSwsdl#SMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> sendMultiSMSAsync(string domain, string username, string password, string from, string to, string texts, int isflash);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SMSwsdl#GetCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCreditAsync(string domain, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SMSwsdl#getDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(account))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(message))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(delivery))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<wrmsms.delivery[]> getDeliveryAsync(string domain, string username, string password, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SMSwsdl#getDeliveryMulti", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(account))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(message))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(delivery))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<wrmsms.delivery[]> getDeliveryMultiAsync(string domain, string username, string password, int id);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:SMSwsdl#checkReceive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(account))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(message))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(delivery))]
        System.Threading.Tasks.Task<wrmsms.checkReceiveResponse> checkReceiveAsync(wrmsms.checkReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wrm-sms.ir/APPs/SMS/WebService.php/getMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(account))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(message))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(delivery))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<wrmsms.message[]> getMessagesAsync(string domain, string username, string password, string smsType, string start, string count, string from);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SMSwsdl#getMessagesCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(account))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(message))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(delivery))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getMessagesCountAsync(string domain, string username, string password, string smsType, string from, string box);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SMSwsdl#removeMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(account))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(message))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(delivery))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> removeMessageAsync(string domain, string username, string password, string ids, string smsType);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://wrm-sms.ir/APPs/SMS/WebService.php/getPayAccounts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(account))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(message))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(delivery))]
        System.Threading.Tasks.Task<wrmsms.getPayAccountsResponse> getPayAccountsAsync(wrmsms.getPayAccountsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:SMSwsdl#SMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(account))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(message))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(delivery))]
        System.Threading.Tasks.Task<wrmsms.payRequestResponse> payRequestAsync(wrmsms.payRequestRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:SMSwsdl#SMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(account))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(message))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(delivery))]
        System.Threading.Tasks.Task<wrmsms.getCreditPriceResponse> getCreditPriceAsync(wrmsms.getCreditPriceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SMSwsdl")]
    public partial class delivery
    {
        
        private string mobileField;
        
        private int statusField;
        
        /// <remarks/>
        public string mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SMSwsdl")]
    public partial class account
    {
        
        private string acc_idField;
        
        private string titleField;
        
        /// <remarks/>
        public string acc_id
        {
            get
            {
                return this.acc_idField;
            }
            set
            {
                this.acc_idField = value;
            }
        }
        
        /// <remarks/>
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SMSwsdl")]
    public partial class message
    {
        
        private string boxField;
        
        private string textField;
        
        private int sms_idField;
        
        private string send_dateField;
        
        private string creditField;
        
        private string line_noField;
        
        private string mobile_noField;
        
        /// <remarks/>
        public string box
        {
            get
            {
                return this.boxField;
            }
            set
            {
                this.boxField = value;
            }
        }
        
        /// <remarks/>
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public int sms_id
        {
            get
            {
                return this.sms_idField;
            }
            set
            {
                this.sms_idField = value;
            }
        }
        
        /// <remarks/>
        public string send_date
        {
            get
            {
                return this.send_dateField;
            }
            set
            {
                this.send_dateField = value;
            }
        }
        
        /// <remarks/>
        public string credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }
        
        /// <remarks/>
        public string line_no
        {
            get
            {
                return this.line_noField;
            }
            set
            {
                this.line_noField = value;
            }
        }
        
        /// <remarks/>
        public string mobile_no
        {
            get
            {
                return this.mobile_noField;
            }
            set
            {
                this.mobile_noField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkReceive", WrapperNamespace="urn:SMSwsdl", IsWrapped=true)]
    public partial class checkReceiveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mobile_no;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string line_number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string password;
        
        public checkReceiveRequest()
        {
        }
        
        public checkReceiveRequest(string mobile_no, string text, string line_number, string domain, string username, string password)
        {
            this.mobile_no = mobile_no;
            this.text = text;
            this.line_number = line_number;
            this.domain = domain;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkReceiveResponse", WrapperNamespace="urn:SMSwsdl", IsWrapped=true)]
    public partial class checkReceiveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string status;
        
        public checkReceiveResponse()
        {
        }
        
        public checkReceiveResponse(string result, string status)
        {
            this.result = result;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPayAccounts", WrapperNamespace="urn:SMSwsdl", IsWrapped=true)]
    public partial class getPayAccountsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        public getPayAccountsRequest()
        {
        }
        
        public getPayAccountsRequest(string domain, string username, string password)
        {
            this.domain = domain;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPayAccountsResponse", WrapperNamespace="urn:SMSwsdl", IsWrapped=true)]
    public partial class getPayAccountsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public wrmsms.account[] accounts;
        
        public getPayAccountsResponse()
        {
        }
        
        public getPayAccountsResponse(string result, wrmsms.account[] accounts)
        {
            this.result = result;
            this.accounts = accounts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="payRequest", WrapperNamespace="urn:SMSwsdl", IsWrapped=true)]
    public partial class payRequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string account;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string r_url;
        
        public payRequestRequest()
        {
        }
        
        public payRequestRequest(string domain, string username, string password, string account, string amount, string r_url)
        {
            this.domain = domain;
            this.username = username;
            this.password = password;
            this.account = account;
            this.amount = amount;
            this.r_url = r_url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="payRequestResponse", WrapperNamespace="urn:SMSwsdl", IsWrapped=true)]
    public partial class payRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int pay_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string url;
        
        public payRequestResponse()
        {
        }
        
        public payRequestResponse(string result, int pay_id, string url)
        {
            this.result = result;
            this.pay_id = pay_id;
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreditPrice", WrapperNamespace="urn:SMSwsdl", IsWrapped=true)]
    public partial class getCreditPriceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string amount;
        
        public getCreditPriceRequest()
        {
        }
        
        public getCreditPriceRequest(string domain, string username, string password, string amount)
        {
            this.domain = domain;
            this.username = username;
            this.password = password;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreditPriceResponse", WrapperNamespace="urn:SMSwsdl", IsWrapped=true)]
    public partial class getCreditPriceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int price;
        
        public getCreditPriceResponse()
        {
        }
        
        public getCreditPriceResponse(string result, int price)
        {
            this.result = result;
            this.price = price;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface SMSwsdlPortTypeChannel : wrmsms.SMSwsdlPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SMSwsdlPortTypeClient : System.ServiceModel.ClientBase<wrmsms.SMSwsdlPortType>, wrmsms.SMSwsdlPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SMSwsdlPortTypeClient() : 
                base(SMSwsdlPortTypeClient.GetDefaultBinding(), SMSwsdlPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SMSwsdlPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSwsdlPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(SMSwsdlPortTypeClient.GetBindingForEndpoint(endpointConfiguration), SMSwsdlPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSwsdlPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SMSwsdlPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSwsdlPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SMSwsdlPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSwsdlPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> sendSMSAsync(string domain, string username, string password, string from, string to, string text, int isflash)
        {
            return base.Channel.sendSMSAsync(domain, username, password, from, to, text, isflash);
        }
        
        public System.Threading.Tasks.Task<string> sendMultiSMSAsync(string domain, string username, string password, string from, string to, string texts, int isflash)
        {
            return base.Channel.sendMultiSMSAsync(domain, username, password, from, to, texts, isflash);
        }
        
        public System.Threading.Tasks.Task<string> getCreditAsync(string domain, string username, string password)
        {
            return base.Channel.getCreditAsync(domain, username, password);
        }
        
        public System.Threading.Tasks.Task<wrmsms.delivery[]> getDeliveryAsync(string domain, string username, string password, int id)
        {
            return base.Channel.getDeliveryAsync(domain, username, password, id);
        }
        
        public System.Threading.Tasks.Task<wrmsms.delivery[]> getDeliveryMultiAsync(string domain, string username, string password, int id)
        {
            return base.Channel.getDeliveryMultiAsync(domain, username, password, id);
        }
        
        public System.Threading.Tasks.Task<wrmsms.checkReceiveResponse> checkReceiveAsync(wrmsms.checkReceiveRequest request)
        {
            return base.Channel.checkReceiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<wrmsms.message[]> getMessagesAsync(string domain, string username, string password, string smsType, string start, string count, string from)
        {
            return base.Channel.getMessagesAsync(domain, username, password, smsType, start, count, from);
        }
        
        public System.Threading.Tasks.Task<string> getMessagesCountAsync(string domain, string username, string password, string smsType, string from, string box)
        {
            return base.Channel.getMessagesCountAsync(domain, username, password, smsType, from, box);
        }
        
        public System.Threading.Tasks.Task<string> removeMessageAsync(string domain, string username, string password, string ids, string smsType)
        {
            return base.Channel.removeMessageAsync(domain, username, password, ids, smsType);
        }
        
        public System.Threading.Tasks.Task<wrmsms.getPayAccountsResponse> getPayAccountsAsync(wrmsms.getPayAccountsRequest request)
        {
            return base.Channel.getPayAccountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<wrmsms.payRequestResponse> payRequestAsync(wrmsms.payRequestRequest request)
        {
            return base.Channel.payRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<wrmsms.getCreditPriceResponse> getCreditPriceAsync(wrmsms.getCreditPriceRequest request)
        {
            return base.Channel.getCreditPriceAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SMSwsdlPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SMSwsdlPort))
            {
                return new System.ServiceModel.EndpointAddress("http://wrm-sms.ir/APPs/SMS/WebService.php");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SMSwsdlPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.SMSwsdlPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SMSwsdlPortTypeClient.GetEndpointAddress(EndpointConfiguration.SMSwsdlPort);
        }
        
        public enum EndpointConfiguration
        {
            
            SMSwsdlPort,
        }
    }
}
